"""Criar

Revision ID: f0d0b65f4d0d
Revises: 
Create Date: 2025-05-27 07:45:36.886131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d0b65f4d0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nro_emp', sa.Integer(), nullable=True),
    sa.Column('nss_emp', sa.Integer(), nullable=True),
    sa.Column('datainicio', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['nss_emp'], ['empregado.nss'], name='fk_departamento_empregado', use_alter=True),
    sa.PrimaryKeyConstraint('numero')
    )
    op.create_table('dependente',
    sa.Column('nss_emp', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('datanasc', sa.Date(), nullable=True),
    sa.Column('tiporel', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('nss_emp', 'nome')
    )
    op.create_table('empregado',
    sa.Column('nss', sa.Integer(), nullable=False),
    sa.Column('pnome', sa.String(length=50), nullable=False),
    sa.Column('mnome', sa.String(length=50), nullable=True),
    sa.Column('snome', sa.String(length=50), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('datanasc', sa.Date(), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('numero_dep', sa.Integer(), nullable=True),
    sa.Column('nss_supervisor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nss_supervisor'], ['empregado.nss'], ),
    sa.ForeignKeyConstraint(['numero_dep'], ['departamento.numero'], name='fk_empregado_departamento', use_alter=True),
    sa.PrimaryKeyConstraint('nss')
    )
    op.create_table('localizacao',
    sa.Column('localizacao', sa.String(length=100), nullable=False),
    sa.Column('numero_dep', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('localizacao', 'numero_dep')
    )
    op.create_table('trabalha_em',
    sa.Column('nss_emp', sa.Integer(), nullable=False),
    sa.Column('numero_proj', sa.Integer(), nullable=False),
    sa.Column('horas', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('nss_emp', 'numero_proj')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projeto',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('numero_dep', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['numero_dep'], ['departamento.numero'], ),
    sa.PrimaryKeyConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto')
    op.drop_table('user')
    op.drop_table('trabalha_em')
    op.drop_table('localizacao')
    op.drop_table('empregado')
    op.drop_table('dependente')
    op.drop_table('departamento')
    # ### end Alembic commands ###
